### ISSUE TITLE
KDE Plasma 5.24.4 (Kubuntu) crashes when switching audio output on v26

### ISSUE THREAD

**Issue by imagochan** [Zren/plasma-applet-volumewin7mixer#25]
I reported this first here: https://bugs.kde.org/show_bug.cgi?id=457004

the widget crashes plasma when I click the hdmi box icon (or any output) for the second time (happens consistently)

![Screenshot_20220721_225738](https://user-images.githubusercontent.com/30757277/181130598-2baab6ec-2913-4684-8fcb-857cd4ce9de1.png)

Application: plasmashell (5.24.4)

Qt Version: 5.15.3
Frameworks Version: 5.92.0
Operating System: Linux 5.15.0-41-generic x86_64
Windowing System: X11
Distribution: Ubuntu 22.04 LTS
DrKonqi: 5.24.4 [KCrashBackend]

-- Information about the crash:
- What I was doing when the application crashed:
from the desktop panel (the system tray) I opened the widget "win7 volume mixer" clicking the icon, then I clicked the speakers icon (in my case HDMI) to check which audio profile is being used, if I do this again, next time it will crash, this happens everytime

- Custom settings of the application:
no real custom settings, only worth noting is that both the default audio volume icon/item and the win7 volume mixer are enabled at the same time (I have both icons active in my system tray, which is how I want it) and I'm also using version 26 (v26)

The crash can be reproduced every time.

-- Backtrace:
Application: Plasma (plasmashell), signal: Segmentation fault

[KCrash Handler]
#4  0x00007f924442051b in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f924443190f in QWidget::removeAction(QAction*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f9229dd0d98 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/components/libplasmacomponentsplugin.so
#7  0x00007f92443f8713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f9243701e2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f9243737437 in QObjectPrivate::setParent_helper(QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f9243737948 in QObject::~QObject() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f9229dcb82b in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/components/libplasmacomponentsplugin.so
#12 0x00007f924372f1b3 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f92443f8713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f9243701e2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f9243704f17 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f924375ba57 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f9241addd1b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f9241b326f8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f9241adb3c3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f924375b0a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f924370074b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f9243708ce4 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x0000560fd3d60dce in ?? ()
#24 0x00007f924301dd90 in __libc_start_call_main (main=main@entry=0x560fd3d5ff70, argc=argc@entry=1, argv=argv@entry=0x7ffefd8fc0b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#25 0x00007f924301de40 in __libc_start_main_impl (main=0x560fd3d5ff70, argc=1, argv=0x7ffefd8fc0b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffefd8fc0a8) at ../csu/libc-start.c:392
#26 0x0000560fd3d60ef5 in ?? ()
[Inferior 1 (process 1180) detached]

Possible duplicates by query: [bug 456990](https://bugs.kde.org/show_bug.cgi?id=456990), [bug 456947](https://bugs.kde.org/show_bug.cgi?id=456947), [bug 456940](https://bugs.kde.org/show_bug.cgi?id=456940), [bug 456743](https://bugs.kde.org/show_bug.cgi?id=456743), [bug 456720](https://bugs.kde.org/show_bug.cgi?id=456720).

Reported using DrKonqi

**Comment by chrapuch** [comment]
Yup, same for me. Every 2nd click on the icon kills plasma.

- Operating System: MX Linux 23
- KDE Plasma Version: 5.27.5
- KDE Frameworks Version: 5.103.0
- Qt Version: 5.15.8
- Kernel Version: 6.1.0-10-amd64 (64-bit)
- Graphics Platform: X11


```
Application: Plasma (plasmashell), signal: Segmentation fault

[KCrash Handler]
#4  0x00007f1f5c78a56b in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f1f5c79b49b in QWidget::removeAction(QAction*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f1f2d93ff94 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/components/libplasmacomponentsplugin.so
#7  0x00007f1f5c762fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f1f5bab1738 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f1f5bae6b47 in QObjectPrivate::setParent_helper(QObject*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f1f5bae70c3 in QObject::~QObject() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f1f2d93cac6 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/components/libplasmacomponentsplugin.so
#12 0x00007f1f5badd4ff in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f1f5c762fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f1f5bab1738 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f1f5bab46c1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f1f5bb0a193 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f1f5a3dc7a9 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f1f5a3dca38 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f1f5a3dcacc in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f1f5bb09876 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f1f5bab01bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f1f5bab8316 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x0000561c77610dc3 in  ()
#24 0x00007f1f5b64624a in  () at /lib/x86_64-linux-gnu/libc.so.6
#25 0x00007f1f5b646305 in __libc_start_main () at /lib/x86_64-linux-gnu/libc.so.6
#26 0x0000561c77610ee1 in  ()
[Inferior 1 (process 3892) detached]
```
